#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICPClientLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICPClient")]
	public partial class ICPClientDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InserttblLimit(tblLimit instance);
    partial void UpdatetblLimit(tblLimit instance);
    partial void DeletetblLimit(tblLimit instance);
    partial void InsertLocalCooler(LocalCooler instance);
    partial void UpdateLocalCooler(LocalCooler instance);
    partial void DeleteLocalCooler(LocalCooler instance);
    partial void InsertLocaltblIntermeditateICP(LocaltblIntermeditateICP instance);
    partial void UpdateLocaltblIntermeditateICP(LocaltblIntermeditateICP instance);
    partial void DeleteLocaltblIntermeditateICP(LocaltblIntermeditateICP instance);
    #endregion
		
		public ICPClientDataContext() : 
				base(global::ICPClientLinq.Properties.Settings.Default.ICPClientConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ICPClientDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICPClientDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICPClientDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ICPClientDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Log> Logs
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<tblLimit> tblLimits
		{
			get
			{
				return this.GetTable<tblLimit>();
			}
		}
		
		public System.Data.Linq.Table<LocalCooler> LocalCoolers
		{
			get
			{
				return this.GetTable<LocalCooler>();
			}
		}
		
		public System.Data.Linq.Table<LocaltblIntermeditateICP> LocaltblIntermeditateICPs
		{
			get
			{
				return this.GetTable<LocaltblIntermeditateICP>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Log]")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<int> _SeverityCode;
		
		private string _Severity;
		
		private string _Msg;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    partial void OnSeverityCodeChanging(System.Nullable<int> value);
    partial void OnSeverityCodeChanged();
    partial void OnSeverityChanging(string value);
    partial void OnSeverityChanged();
    partial void OnMsgChanging(string value);
    partial void OnMsgChanged();
    #endregion
		
		public Log()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeverityCode", DbType="Int")]
		public System.Nullable<int> SeverityCode
		{
			get
			{
				return this._SeverityCode;
			}
			set
			{
				if ((this._SeverityCode != value))
				{
					this.OnSeverityCodeChanging(value);
					this.SendPropertyChanging();
					this._SeverityCode = value;
					this.SendPropertyChanged("SeverityCode");
					this.OnSeverityCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Severity", DbType="VarChar(100)")]
		public string Severity
		{
			get
			{
				return this._Severity;
			}
			set
			{
				if ((this._Severity != value))
				{
					this.OnSeverityChanging(value);
					this.SendPropertyChanging();
					this._Severity = value;
					this.SendPropertyChanged("Severity");
					this.OnSeverityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msg", DbType="VarChar(250)")]
		public string Msg
		{
			get
			{
				return this._Msg;
			}
			set
			{
				if ((this._Msg != value))
				{
					this.OnMsgChanging(value);
					this.SendPropertyChanging();
					this._Msg = value;
					this.SendPropertyChanged("Msg");
					this.OnMsgChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLimits")]
	public partial class tblLimit : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Element;
		
		private decimal _Reporting;
		
		private decimal _MDL;
		
		private System.Nullable<decimal> _DvsTDifference;
		
		private int _LimitID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnElementChanging(string value);
    partial void OnElementChanged();
    partial void OnReportingChanging(decimal value);
    partial void OnReportingChanged();
    partial void OnMDLChanging(decimal value);
    partial void OnMDLChanged();
    partial void OnDvsTDifferenceChanging(System.Nullable<decimal> value);
    partial void OnDvsTDifferenceChanged();
    partial void OnLimitIDChanging(int value);
    partial void OnLimitIDChanged();
    #endregion
		
		public tblLimit()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Element", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string Element
		{
			get
			{
				return this._Element;
			}
			set
			{
				if ((this._Element != value))
				{
					this.OnElementChanging(value);
					this.SendPropertyChanging();
					this._Element = value;
					this.SendPropertyChanged("Element");
					this.OnElementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reporting", DbType="Decimal(16,2) NOT NULL")]
		public decimal Reporting
		{
			get
			{
				return this._Reporting;
			}
			set
			{
				if ((this._Reporting != value))
				{
					this.OnReportingChanging(value);
					this.SendPropertyChanging();
					this._Reporting = value;
					this.SendPropertyChanged("Reporting");
					this.OnReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MDL", DbType="Decimal(16,2) NOT NULL")]
		public decimal MDL
		{
			get
			{
				return this._MDL;
			}
			set
			{
				if ((this._MDL != value))
				{
					this.OnMDLChanging(value);
					this.SendPropertyChanging();
					this._MDL = value;
					this.SendPropertyChanged("MDL");
					this.OnMDLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DvsTDifference", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> DvsTDifference
		{
			get
			{
				return this._DvsTDifference;
			}
			set
			{
				if ((this._DvsTDifference != value))
				{
					this.OnDvsTDifferenceChanging(value);
					this.SendPropertyChanging();
					this._DvsTDifference = value;
					this.SendPropertyChanged("DvsTDifference");
					this.OnDvsTDifferenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LimitID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LimitID
		{
			get
			{
				return this._LimitID;
			}
			set
			{
				if ((this._LimitID != value))
				{
					this.OnLimitIDChanging(value);
					this.SendPropertyChanging();
					this._LimitID = value;
					this.SendPropertyChanged("LimitID");
					this.OnLimitIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LocalCooler")]
	public partial class LocalCooler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CoolerID;
		
		private string _BarCode;
		
		private string _CODE;
		
		private string _DUPLICATE;
		
		private System.Nullable<decimal> _AL_D;
		
		private System.Nullable<decimal> _AL_T;
		
		private System.Nullable<decimal> _AS_D;
		
		private System.Nullable<decimal> _AS_T;
		
		private System.Nullable<decimal> _CA_D;
		
		private System.Nullable<decimal> _CA_T;
		
		private System.Nullable<decimal> _CD_D;
		
		private System.Nullable<decimal> _CD_T;
		
		private System.Nullable<decimal> _CU_D;
		
		private System.Nullable<decimal> _CU_T;
		
		private System.Nullable<decimal> _FE_D;
		
		private System.Nullable<decimal> _FE_T;
		
		private System.Nullable<decimal> _K_D;
		
		private System.Nullable<decimal> _K_T;
		
		private System.Nullable<decimal> _MG_D;
		
		private System.Nullable<decimal> _MG_T;
		
		private System.Nullable<decimal> _MN_D;
		
		private System.Nullable<decimal> _MN_T;
		
		private System.Nullable<decimal> _NA_D;
		
		private System.Nullable<decimal> _NA_T;
		
		private System.Nullable<decimal> _PB_D;
		
		private System.Nullable<decimal> _PB_T;
		
		private System.Nullable<decimal> _SE_D;
		
		private System.Nullable<decimal> _SE_T;
		
		private System.Nullable<decimal> _ZN_D;
		
		private System.Nullable<decimal> _ZN_T;
		
		private System.Nullable<System.DateTime> _ANADATE;
		
		private bool _COMPLETE;
		
		private System.Nullable<System.DateTime> _DATE_SENT;
		
		private string _Comments;
		
		private System.Nullable<decimal> _PassValStep;
		
		private bool _Reviewed;
		
		private string _FailedChems;
		
		private System.Nullable<int> _tblSampleID;
		
		private bool _Bottle_Complete;
		
		private bool _Cooler;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _CreatedWhen;
		
		private string _ModifiedBy;
		
		private System.Nullable<System.DateTime> _ModifiedWhen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCoolerIDChanging(int value);
    partial void OnCoolerIDChanged();
    partial void OnBarCodeChanging(string value);
    partial void OnBarCodeChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnDUPLICATEChanging(string value);
    partial void OnDUPLICATEChanged();
    partial void OnAL_DChanging(System.Nullable<decimal> value);
    partial void OnAL_DChanged();
    partial void OnAL_TChanging(System.Nullable<decimal> value);
    partial void OnAL_TChanged();
    partial void OnAS_DChanging(System.Nullable<decimal> value);
    partial void OnAS_DChanged();
    partial void OnAS_TChanging(System.Nullable<decimal> value);
    partial void OnAS_TChanged();
    partial void OnCA_DChanging(System.Nullable<decimal> value);
    partial void OnCA_DChanged();
    partial void OnCA_TChanging(System.Nullable<decimal> value);
    partial void OnCA_TChanged();
    partial void OnCD_DChanging(System.Nullable<decimal> value);
    partial void OnCD_DChanged();
    partial void OnCD_TChanging(System.Nullable<decimal> value);
    partial void OnCD_TChanged();
    partial void OnCU_DChanging(System.Nullable<decimal> value);
    partial void OnCU_DChanged();
    partial void OnCU_TChanging(System.Nullable<decimal> value);
    partial void OnCU_TChanged();
    partial void OnFE_DChanging(System.Nullable<decimal> value);
    partial void OnFE_DChanged();
    partial void OnFE_TChanging(System.Nullable<decimal> value);
    partial void OnFE_TChanged();
    partial void OnK_DChanging(System.Nullable<decimal> value);
    partial void OnK_DChanged();
    partial void OnK_TChanging(System.Nullable<decimal> value);
    partial void OnK_TChanged();
    partial void OnMG_DChanging(System.Nullable<decimal> value);
    partial void OnMG_DChanged();
    partial void OnMG_TChanging(System.Nullable<decimal> value);
    partial void OnMG_TChanged();
    partial void OnMN_DChanging(System.Nullable<decimal> value);
    partial void OnMN_DChanged();
    partial void OnMN_TChanging(System.Nullable<decimal> value);
    partial void OnMN_TChanged();
    partial void OnNA_DChanging(System.Nullable<decimal> value);
    partial void OnNA_DChanged();
    partial void OnNA_TChanging(System.Nullable<decimal> value);
    partial void OnNA_TChanged();
    partial void OnPB_DChanging(System.Nullable<decimal> value);
    partial void OnPB_DChanged();
    partial void OnPB_TChanging(System.Nullable<decimal> value);
    partial void OnPB_TChanged();
    partial void OnSE_DChanging(System.Nullable<decimal> value);
    partial void OnSE_DChanged();
    partial void OnSE_TChanging(System.Nullable<decimal> value);
    partial void OnSE_TChanged();
    partial void OnZN_DChanging(System.Nullable<decimal> value);
    partial void OnZN_DChanged();
    partial void OnZN_TChanging(System.Nullable<decimal> value);
    partial void OnZN_TChanged();
    partial void OnANADATEChanging(System.Nullable<System.DateTime> value);
    partial void OnANADATEChanged();
    partial void OnCOMPLETEChanging(bool value);
    partial void OnCOMPLETEChanged();
    partial void OnDATE_SENTChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_SENTChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnPassValStepChanging(System.Nullable<decimal> value);
    partial void OnPassValStepChanged();
    partial void OnReviewedChanging(bool value);
    partial void OnReviewedChanged();
    partial void OnFailedChemsChanging(string value);
    partial void OnFailedChemsChanged();
    partial void OntblSampleIDChanging(System.Nullable<int> value);
    partial void OntblSampleIDChanged();
    partial void OnBottle_CompleteChanging(bool value);
    partial void OnBottle_CompleteChanged();
    partial void OnCoolerChanging(bool value);
    partial void OnCoolerChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnCreatedWhenChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedWhenChanged();
    partial void OnModifiedByChanging(string value);
    partial void OnModifiedByChanged();
    partial void OnModifiedWhenChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedWhenChanged();
    #endregion
		
		public LocalCooler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoolerID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CoolerID
		{
			get
			{
				return this._CoolerID;
			}
			set
			{
				if ((this._CoolerID != value))
				{
					this.OnCoolerIDChanging(value);
					this.SendPropertyChanging();
					this._CoolerID = value;
					this.SendPropertyChanged("CoolerID");
					this.OnCoolerIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(30)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUPLICATE", DbType="NVarChar(2)")]
		public string DUPLICATE
		{
			get
			{
				return this._DUPLICATE;
			}
			set
			{
				if ((this._DUPLICATE != value))
				{
					this.OnDUPLICATEChanging(value);
					this.SendPropertyChanging();
					this._DUPLICATE = value;
					this.SendPropertyChanged("DUPLICATE");
					this.OnDUPLICATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> AL_D
		{
			get
			{
				return this._AL_D;
			}
			set
			{
				if ((this._AL_D != value))
				{
					this.OnAL_DChanging(value);
					this.SendPropertyChanging();
					this._AL_D = value;
					this.SendPropertyChanged("AL_D");
					this.OnAL_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> AL_T
		{
			get
			{
				return this._AL_T;
			}
			set
			{
				if ((this._AL_T != value))
				{
					this.OnAL_TChanging(value);
					this.SendPropertyChanging();
					this._AL_T = value;
					this.SendPropertyChanged("AL_T");
					this.OnAL_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AS_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> AS_D
		{
			get
			{
				return this._AS_D;
			}
			set
			{
				if ((this._AS_D != value))
				{
					this.OnAS_DChanging(value);
					this.SendPropertyChanging();
					this._AS_D = value;
					this.SendPropertyChanged("AS_D");
					this.OnAS_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AS_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> AS_T
		{
			get
			{
				return this._AS_T;
			}
			set
			{
				if ((this._AS_T != value))
				{
					this.OnAS_TChanging(value);
					this.SendPropertyChanging();
					this._AS_T = value;
					this.SendPropertyChanged("AS_T");
					this.OnAS_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> CA_D
		{
			get
			{
				return this._CA_D;
			}
			set
			{
				if ((this._CA_D != value))
				{
					this.OnCA_DChanging(value);
					this.SendPropertyChanging();
					this._CA_D = value;
					this.SendPropertyChanged("CA_D");
					this.OnCA_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> CA_T
		{
			get
			{
				return this._CA_T;
			}
			set
			{
				if ((this._CA_T != value))
				{
					this.OnCA_TChanging(value);
					this.SendPropertyChanging();
					this._CA_T = value;
					this.SendPropertyChanged("CA_T");
					this.OnCA_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_D", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CD_D
		{
			get
			{
				return this._CD_D;
			}
			set
			{
				if ((this._CD_D != value))
				{
					this.OnCD_DChanging(value);
					this.SendPropertyChanging();
					this._CD_D = value;
					this.SendPropertyChanged("CD_D");
					this.OnCD_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_T", DbType="Decimal(12,2)")]
		public System.Nullable<decimal> CD_T
		{
			get
			{
				return this._CD_T;
			}
			set
			{
				if ((this._CD_T != value))
				{
					this.OnCD_TChanging(value);
					this.SendPropertyChanging();
					this._CD_T = value;
					this.SendPropertyChanged("CD_T");
					this.OnCD_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_D", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> CU_D
		{
			get
			{
				return this._CU_D;
			}
			set
			{
				if ((this._CU_D != value))
				{
					this.OnCU_DChanging(value);
					this.SendPropertyChanging();
					this._CU_D = value;
					this.SendPropertyChanged("CU_D");
					this.OnCU_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_T", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> CU_T
		{
			get
			{
				return this._CU_T;
			}
			set
			{
				if ((this._CU_T != value))
				{
					this.OnCU_TChanging(value);
					this.SendPropertyChanging();
					this._CU_T = value;
					this.SendPropertyChanged("CU_T");
					this.OnCU_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FE_D
		{
			get
			{
				return this._FE_D;
			}
			set
			{
				if ((this._FE_D != value))
				{
					this.OnFE_DChanging(value);
					this.SendPropertyChanging();
					this._FE_D = value;
					this.SendPropertyChanged("FE_D");
					this.OnFE_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> FE_T
		{
			get
			{
				return this._FE_T;
			}
			set
			{
				if ((this._FE_T != value))
				{
					this.OnFE_TChanging(value);
					this.SendPropertyChanging();
					this._FE_T = value;
					this.SendPropertyChanged("FE_T");
					this.OnFE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_K_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> K_D
		{
			get
			{
				return this._K_D;
			}
			set
			{
				if ((this._K_D != value))
				{
					this.OnK_DChanging(value);
					this.SendPropertyChanging();
					this._K_D = value;
					this.SendPropertyChanged("K_D");
					this.OnK_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_K_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> K_T
		{
			get
			{
				return this._K_T;
			}
			set
			{
				if ((this._K_T != value))
				{
					this.OnK_TChanging(value);
					this.SendPropertyChanging();
					this._K_T = value;
					this.SendPropertyChanged("K_T");
					this.OnK_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MG_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> MG_D
		{
			get
			{
				return this._MG_D;
			}
			set
			{
				if ((this._MG_D != value))
				{
					this.OnMG_DChanging(value);
					this.SendPropertyChanging();
					this._MG_D = value;
					this.SendPropertyChanged("MG_D");
					this.OnMG_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MG_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> MG_T
		{
			get
			{
				return this._MG_T;
			}
			set
			{
				if ((this._MG_T != value))
				{
					this.OnMG_TChanging(value);
					this.SendPropertyChanging();
					this._MG_T = value;
					this.SendPropertyChanged("MG_T");
					this.OnMG_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MN_D", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> MN_D
		{
			get
			{
				return this._MN_D;
			}
			set
			{
				if ((this._MN_D != value))
				{
					this.OnMN_DChanging(value);
					this.SendPropertyChanging();
					this._MN_D = value;
					this.SendPropertyChanged("MN_D");
					this.OnMN_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MN_T", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> MN_T
		{
			get
			{
				return this._MN_T;
			}
			set
			{
				if ((this._MN_T != value))
				{
					this.OnMN_TChanging(value);
					this.SendPropertyChanging();
					this._MN_T = value;
					this.SendPropertyChanged("MN_T");
					this.OnMN_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NA_D", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> NA_D
		{
			get
			{
				return this._NA_D;
			}
			set
			{
				if ((this._NA_D != value))
				{
					this.OnNA_DChanging(value);
					this.SendPropertyChanging();
					this._NA_D = value;
					this.SendPropertyChanged("NA_D");
					this.OnNA_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NA_T", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> NA_T
		{
			get
			{
				return this._NA_T;
			}
			set
			{
				if ((this._NA_T != value))
				{
					this.OnNA_TChanging(value);
					this.SendPropertyChanging();
					this._NA_T = value;
					this.SendPropertyChanged("NA_T");
					this.OnNA_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PB_D", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> PB_D
		{
			get
			{
				return this._PB_D;
			}
			set
			{
				if ((this._PB_D != value))
				{
					this.OnPB_DChanging(value);
					this.SendPropertyChanging();
					this._PB_D = value;
					this.SendPropertyChanged("PB_D");
					this.OnPB_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PB_T", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> PB_T
		{
			get
			{
				return this._PB_T;
			}
			set
			{
				if ((this._PB_T != value))
				{
					this.OnPB_TChanging(value);
					this.SendPropertyChanging();
					this._PB_T = value;
					this.SendPropertyChanged("PB_T");
					this.OnPB_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SE_D", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> SE_D
		{
			get
			{
				return this._SE_D;
			}
			set
			{
				if ((this._SE_D != value))
				{
					this.OnSE_DChanging(value);
					this.SendPropertyChanging();
					this._SE_D = value;
					this.SendPropertyChanged("SE_D");
					this.OnSE_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SE_T", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> SE_T
		{
			get
			{
				return this._SE_T;
			}
			set
			{
				if ((this._SE_T != value))
				{
					this.OnSE_TChanging(value);
					this.SendPropertyChanging();
					this._SE_T = value;
					this.SendPropertyChanged("SE_T");
					this.OnSE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZN_D", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> ZN_D
		{
			get
			{
				return this._ZN_D;
			}
			set
			{
				if ((this._ZN_D != value))
				{
					this.OnZN_DChanging(value);
					this.SendPropertyChanging();
					this._ZN_D = value;
					this.SendPropertyChanged("ZN_D");
					this.OnZN_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZN_T", DbType="Decimal(12,1)")]
		public System.Nullable<decimal> ZN_T
		{
			get
			{
				return this._ZN_T;
			}
			set
			{
				if ((this._ZN_T != value))
				{
					this.OnZN_TChanging(value);
					this.SendPropertyChanging();
					this._ZN_T = value;
					this.SendPropertyChanged("ZN_T");
					this.OnZN_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ANADATE
		{
			get
			{
				return this._ANADATE;
			}
			set
			{
				if ((this._ANADATE != value))
				{
					this.OnANADATEChanging(value);
					this.SendPropertyChanging();
					this._ANADATE = value;
					this.SendPropertyChanged("ANADATE");
					this.OnANADATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETE", DbType="Bit NOT NULL")]
		public bool COMPLETE
		{
			get
			{
				return this._COMPLETE;
			}
			set
			{
				if ((this._COMPLETE != value))
				{
					this.OnCOMPLETEChanging(value);
					this.SendPropertyChanging();
					this._COMPLETE = value;
					this.SendPropertyChanged("COMPLETE");
					this.OnCOMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SENT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_SENT
		{
			get
			{
				return this._DATE_SENT;
			}
			set
			{
				if ((this._DATE_SENT != value))
				{
					this.OnDATE_SENTChanging(value);
					this.SendPropertyChanging();
					this._DATE_SENT = value;
					this.SendPropertyChanged("DATE_SENT");
					this.OnDATE_SENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(100)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassValStep", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PassValStep
		{
			get
			{
				return this._PassValStep;
			}
			set
			{
				if ((this._PassValStep != value))
				{
					this.OnPassValStepChanging(value);
					this.SendPropertyChanging();
					this._PassValStep = value;
					this.SendPropertyChanged("PassValStep");
					this.OnPassValStepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed", DbType="Bit NOT NULL")]
		public bool Reviewed
		{
			get
			{
				return this._Reviewed;
			}
			set
			{
				if ((this._Reviewed != value))
				{
					this.OnReviewedChanging(value);
					this.SendPropertyChanging();
					this._Reviewed = value;
					this.SendPropertyChanged("Reviewed");
					this.OnReviewedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedChems", DbType="NVarChar(200)")]
		public string FailedChems
		{
			get
			{
				return this._FailedChems;
			}
			set
			{
				if ((this._FailedChems != value))
				{
					this.OnFailedChemsChanging(value);
					this.SendPropertyChanging();
					this._FailedChems = value;
					this.SendPropertyChanged("FailedChems");
					this.OnFailedChemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tblSampleID", DbType="Int")]
		public System.Nullable<int> tblSampleID
		{
			get
			{
				return this._tblSampleID;
			}
			set
			{
				if ((this._tblSampleID != value))
				{
					this.OntblSampleIDChanging(value);
					this.SendPropertyChanging();
					this._tblSampleID = value;
					this.SendPropertyChanged("tblSampleID");
					this.OntblSampleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bottle_Complete", DbType="Bit NOT NULL")]
		public bool Bottle_Complete
		{
			get
			{
				return this._Bottle_Complete;
			}
			set
			{
				if ((this._Bottle_Complete != value))
				{
					this.OnBottle_CompleteChanging(value);
					this.SendPropertyChanging();
					this._Bottle_Complete = value;
					this.SendPropertyChanged("Bottle_Complete");
					this.OnBottle_CompleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cooler", DbType="Bit NOT NULL")]
		public bool Cooler
		{
			get
			{
				return this._Cooler;
			}
			set
			{
				if ((this._Cooler != value))
				{
					this.OnCoolerChanging(value);
					this.SendPropertyChanging();
					this._Cooler = value;
					this.SendPropertyChanged("Cooler");
					this.OnCoolerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(20)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedWhen", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedWhen
		{
			get
			{
				return this._CreatedWhen;
			}
			set
			{
				if ((this._CreatedWhen != value))
				{
					this.OnCreatedWhenChanging(value);
					this.SendPropertyChanging();
					this._CreatedWhen = value;
					this.SendPropertyChanged("CreatedWhen");
					this.OnCreatedWhenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedBy", DbType="NVarChar(20)")]
		public string ModifiedBy
		{
			get
			{
				return this._ModifiedBy;
			}
			set
			{
				if ((this._ModifiedBy != value))
				{
					this.OnModifiedByChanging(value);
					this.SendPropertyChanging();
					this._ModifiedBy = value;
					this.SendPropertyChanged("ModifiedBy");
					this.OnModifiedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedWhen", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedWhen
		{
			get
			{
				return this._ModifiedWhen;
			}
			set
			{
				if ((this._ModifiedWhen != value))
				{
					this.OnModifiedWhenChanging(value);
					this.SendPropertyChanging();
					this._ModifiedWhen = value;
					this.SendPropertyChanged("ModifiedWhen");
					this.OnModifiedWhenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LocaltblIntermeditateICP")]
	public partial class LocaltblIntermeditateICP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IntermeditateIcpID;
		
		private string _BarCode;
		
		private string _Code;
		
		private System.Nullable<System.DateTime> _Anadate;
		
		private string _Element;
		
		private System.Nullable<short> _IndexLine;
		
		private string _Wavelength;
		
		private System.Nullable<decimal> _AverageResult;
		
		private string _FailFlags;
		
		private string _CheckFlag;
		
		private string _Duplicate;
		
		private System.Nullable<bool> _Filtered;
		
		private System.Nullable<bool> _DeleteFlag;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIntermeditateIcpIDChanging(int value);
    partial void OnIntermeditateIcpIDChanged();
    partial void OnBarCodeChanging(string value);
    partial void OnBarCodeChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnAnadateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnadateChanged();
    partial void OnElementChanging(string value);
    partial void OnElementChanged();
    partial void OnIndexLineChanging(System.Nullable<short> value);
    partial void OnIndexLineChanged();
    partial void OnWavelengthChanging(string value);
    partial void OnWavelengthChanged();
    partial void OnAverageResultChanging(System.Nullable<decimal> value);
    partial void OnAverageResultChanged();
    partial void OnFailFlagsChanging(string value);
    partial void OnFailFlagsChanged();
    partial void OnCheckFlagChanging(string value);
    partial void OnCheckFlagChanged();
    partial void OnDuplicateChanging(string value);
    partial void OnDuplicateChanged();
    partial void OnFilteredChanging(System.Nullable<bool> value);
    partial void OnFilteredChanged();
    partial void OnDeleteFlagChanging(System.Nullable<bool> value);
    partial void OnDeleteFlagChanged();
    #endregion
		
		public LocaltblIntermeditateICP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntermeditateIcpID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IntermeditateIcpID
		{
			get
			{
				return this._IntermeditateIcpID;
			}
			set
			{
				if ((this._IntermeditateIcpID != value))
				{
					this.OnIntermeditateIcpIDChanging(value);
					this.SendPropertyChanging();
					this._IntermeditateIcpID = value;
					this.SendPropertyChanged("IntermeditateIcpID");
					this.OnIntermeditateIcpIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="NVarChar(20)")]
		public string BarCode
		{
			get
			{
				return this._BarCode;
			}
			set
			{
				if ((this._BarCode != value))
				{
					this.OnBarCodeChanging(value);
					this.SendPropertyChanging();
					this._BarCode = value;
					this.SendPropertyChanged("BarCode");
					this.OnBarCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(10)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anadate", DbType="DateTime")]
		public System.Nullable<System.DateTime> Anadate
		{
			get
			{
				return this._Anadate;
			}
			set
			{
				if ((this._Anadate != value))
				{
					this.OnAnadateChanging(value);
					this.SendPropertyChanging();
					this._Anadate = value;
					this.SendPropertyChanged("Anadate");
					this.OnAnadateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Element", DbType="NVarChar(3)")]
		public string Element
		{
			get
			{
				return this._Element;
			}
			set
			{
				if ((this._Element != value))
				{
					this.OnElementChanging(value);
					this.SendPropertyChanging();
					this._Element = value;
					this.SendPropertyChanged("Element");
					this.OnElementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndexLine", DbType="SmallInt")]
		public System.Nullable<short> IndexLine
		{
			get
			{
				return this._IndexLine;
			}
			set
			{
				if ((this._IndexLine != value))
				{
					this.OnIndexLineChanging(value);
					this.SendPropertyChanging();
					this._IndexLine = value;
					this.SendPropertyChanged("IndexLine");
					this.OnIndexLineChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wavelength", DbType="NChar(8)")]
		public string Wavelength
		{
			get
			{
				return this._Wavelength;
			}
			set
			{
				if ((this._Wavelength != value))
				{
					this.OnWavelengthChanging(value);
					this.SendPropertyChanging();
					this._Wavelength = value;
					this.SendPropertyChanged("Wavelength");
					this.OnWavelengthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageResult", DbType="Decimal(16,2)")]
		public System.Nullable<decimal> AverageResult
		{
			get
			{
				return this._AverageResult;
			}
			set
			{
				if ((this._AverageResult != value))
				{
					this.OnAverageResultChanging(value);
					this.SendPropertyChanging();
					this._AverageResult = value;
					this.SendPropertyChanged("AverageResult");
					this.OnAverageResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailFlags", DbType="NVarChar(6)")]
		public string FailFlags
		{
			get
			{
				return this._FailFlags;
			}
			set
			{
				if ((this._FailFlags != value))
				{
					this.OnFailFlagsChanging(value);
					this.SendPropertyChanging();
					this._FailFlags = value;
					this.SendPropertyChanged("FailFlags");
					this.OnFailFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckFlag", DbType="NVarChar(1)")]
		public string CheckFlag
		{
			get
			{
				return this._CheckFlag;
			}
			set
			{
				if ((this._CheckFlag != value))
				{
					this.OnCheckFlagChanging(value);
					this.SendPropertyChanging();
					this._CheckFlag = value;
					this.SendPropertyChanged("CheckFlag");
					this.OnCheckFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Duplicate", DbType="NVarChar(10)")]
		public string Duplicate
		{
			get
			{
				return this._Duplicate;
			}
			set
			{
				if ((this._Duplicate != value))
				{
					this.OnDuplicateChanging(value);
					this.SendPropertyChanging();
					this._Duplicate = value;
					this.SendPropertyChanged("Duplicate");
					this.OnDuplicateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filtered", DbType="Bit")]
		public System.Nullable<bool> Filtered
		{
			get
			{
				return this._Filtered;
			}
			set
			{
				if ((this._Filtered != value))
				{
					this.OnFilteredChanging(value);
					this.SendPropertyChanging();
					this._Filtered = value;
					this.SendPropertyChanged("Filtered");
					this.OnFilteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeleteFlag", DbType="Bit")]
		public System.Nullable<bool> DeleteFlag
		{
			get
			{
				return this._DeleteFlag;
			}
			set
			{
				if ((this._DeleteFlag != value))
				{
					this.OnDeleteFlagChanging(value);
					this.SendPropertyChanging();
					this._DeleteFlag = value;
					this.SendPropertyChanged("DeleteFlag");
					this.OnDeleteFlagChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
