#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICPClientLinq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="rwprod")]
	public partial class RiverwatchDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblMetalBarCode(tblMetalBarCode instance);
    partial void UpdatetblMetalBarCode(tblMetalBarCode instance);
    partial void DeletetblMetalBarCode(tblMetalBarCode instance);
    partial void UpdatetblInboundICP(tblInboundICP instance);
    partial void DeletetblInboundICP(tblInboundICP instance);
    partial void InserttblChemValue(tblChemValue instance);
    partial void UpdatetblChemValue(tblChemValue instance);
    partial void DeletetblChemValue(tblChemValue instance);
    partial void InserttblChemSamp(tblChemSamp instance);
    partial void UpdatetblChemSamp(tblChemSamp instance);
    partial void DeletetblChemSamp(tblChemSamp instance);
    partial void InserttblSample(tblSample instance);
    partial void UpdatetblSample(tblSample instance);
    partial void DeletetblSample(tblSample instance);
    #endregion
		
		public RiverwatchDataContext() : 
				base(global::ICPClientLinq.Properties.Settings.Default.RiverwatchConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RiverwatchDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RiverwatchDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RiverwatchDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RiverwatchDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblMetalBarCode> tblMetalBarCodes
		{
			get
			{
				return this.GetTable<tblMetalBarCode>();
			}
		}
		
		public System.Data.Linq.Table<tblInboundICP> tblInboundICPs
		{
			get
			{
				return this.GetTable<tblInboundICP>();
			}
		}
		
		public System.Data.Linq.Table<tblChemValue> tblChemValues
		{
			get
			{
				return this.GetTable<tblChemValue>();
			}
		}
		
		public System.Data.Linq.Table<tblChemSamp> tblChemSamps
		{
			get
			{
				return this.GetTable<tblChemSamp>();
			}
		}
		
		public System.Data.Linq.Table<tblSample> tblSamples
		{
			get
			{
				return this.GetTable<tblSample>();
			}
		}
		
		private void InserttblInboundICP(tblInboundICP obj)
		{
			System.Nullable<int> p1 = obj.inbICPID;
			this.instblInboundICP(ref p1, obj.CODE, obj.DUPLICATE, ((System.Nullable<decimal>)(obj.AL_D)), ((System.Nullable<decimal>)(obj.AL_T)), ((System.Nullable<decimal>)(obj.AS_D)), ((System.Nullable<decimal>)(obj.AS_T)), ((System.Nullable<decimal>)(obj.CA_D)), ((System.Nullable<decimal>)(obj.CA_T)), ((System.Nullable<decimal>)(obj.CD_D)), ((System.Nullable<decimal>)(obj.CD_T)), ((System.Nullable<decimal>)(obj.CU_D)), ((System.Nullable<decimal>)(obj.CU_T)), ((System.Nullable<decimal>)(obj.FE_D)), ((System.Nullable<decimal>)(obj.FE_T)), ((System.Nullable<decimal>)(obj.PB_D)), ((System.Nullable<decimal>)(obj.PB_T)), ((System.Nullable<decimal>)(obj.MG_D)), ((System.Nullable<decimal>)(obj.MG_T)), ((System.Nullable<decimal>)(obj.MN_D)), ((System.Nullable<decimal>)(obj.MN_T)), ((System.Nullable<decimal>)(obj.SE_D)), ((System.Nullable<decimal>)(obj.SE_T)), ((System.Nullable<decimal>)(obj.ZN_D)), ((System.Nullable<decimal>)(obj.ZN_T)), ((System.Nullable<System.DateTime>)(obj.ANADATE)), ((System.Nullable<bool>)(obj.COMPLETE)), ((System.Nullable<System.DateTime>)(obj.DATE_SENT)), obj.Comments, ((System.Nullable<decimal>)(obj.PassValStep)), ((System.Nullable<bool>)(obj.Reviewed)), obj.FailedChems, ((System.Nullable<int>)(obj.tblSampleID)), ((System.Nullable<decimal>)(obj.NA_D)), ((System.Nullable<decimal>)(obj.NA_T)), ((System.Nullable<decimal>)(obj.K_D)), ((System.Nullable<decimal>)(obj.K_T)));
			obj.inbICPID = p1.GetValueOrDefault();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.instblInboundICP")]
		public int instblInboundICP(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> inbICPID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODE", DbType="VarChar(30)")] string cODE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DUPLICATE", DbType="Char(2)")] string dUPLICATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_D", DbType="Decimal")] System.Nullable<decimal> aL_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AL_T", DbType="Decimal")] System.Nullable<decimal> aL_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AS_D", DbType="Decimal")] System.Nullable<decimal> aS_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AS_T", DbType="Decimal")] System.Nullable<decimal> aS_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CA_D", DbType="Decimal")] System.Nullable<decimal> cA_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CA_T", DbType="Decimal")] System.Nullable<decimal> cA_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CD_D", DbType="Decimal")] System.Nullable<decimal> cD_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CD_T", DbType="Decimal")] System.Nullable<decimal> cD_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CU_D", DbType="Decimal")] System.Nullable<decimal> cU_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CU_T", DbType="Decimal")] System.Nullable<decimal> cU_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FE_D", DbType="Decimal")] System.Nullable<decimal> fE_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FE_T", DbType="Decimal")] System.Nullable<decimal> fE_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PB_D", DbType="Decimal")] System.Nullable<decimal> pB_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PB_T", DbType="Decimal")] System.Nullable<decimal> pB_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MG_D", DbType="Decimal")] System.Nullable<decimal> mG_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MG_T", DbType="Decimal")] System.Nullable<decimal> mG_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MN_D", DbType="Decimal")] System.Nullable<decimal> mN_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MN_T", DbType="Decimal")] System.Nullable<decimal> mN_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SE_D", DbType="Decimal")] System.Nullable<decimal> sE_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SE_T", DbType="Decimal")] System.Nullable<decimal> sE_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZN_D", DbType="Decimal")] System.Nullable<decimal> zN_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ZN_T", DbType="Decimal")] System.Nullable<decimal> zN_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ANADATE", DbType="DateTime")] System.Nullable<System.DateTime> aNADATE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="COMPLETE", DbType="Bit")] System.Nullable<bool> cOMPLETE, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DATE_SENT", DbType="DateTime")] System.Nullable<System.DateTime> dATE_SENT, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comments", DbType="VarChar(100)")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassValStep", DbType="Decimal")] System.Nullable<decimal> passValStep, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reviewed", DbType="Bit")] System.Nullable<bool> reviewed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FailedChems", DbType="VarChar(200)")] string failedChems, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tblSampleID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NA_D", DbType="Decimal")] System.Nullable<decimal> nA_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NA_T", DbType="Decimal")] System.Nullable<decimal> nA_T, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="K_D", DbType="Decimal")] System.Nullable<decimal> k_D, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="K_T", DbType="Decimal")] System.Nullable<decimal> k_T)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), inbICPID, cODE, dUPLICATE, aL_D, aL_T, aS_D, aS_T, cA_D, cA_T, cD_D, cD_T, cU_D, cU_T, fE_D, fE_T, pB_D, pB_T, mG_D, mG_T, mN_D, mN_T, sE_D, sE_T, zN_D, zN_T, aNADATE, cOMPLETE, dATE_SENT, comments, passValStep, reviewed, failedChems, tblSampleID, nA_D, nA_T, k_D, k_T);
			inbICPID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMetalBarCode")]
	public partial class tblMetalBarCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MetalBarCodeID;
		
		private string _SampleNumber;
		
		private string _NumberSample;
		
		private string _LabID;
		
		private string _Code;
		
		private string _Type;
		
		private bool _Filtered;
		
		private bool _ContainMetal;
		
		private string _BoxNumber;
		
		private bool _Verified;
		
		private System.Nullable<System.DateTime> _LogDate;
		
		private System.Nullable<System.DateTime> _AnalyzeDate;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _UserCreated;
		
		private System.Nullable<System.DateTime> _DateLastModified;
		
		private string _UserLastModified;
		
		private System.Nullable<int> _SampleID;
		
		private EntityRef<tblSample> _tblSample;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMetalBarCodeIDChanging(int value);
    partial void OnMetalBarCodeIDChanged();
    partial void OnSampleNumberChanging(string value);
    partial void OnSampleNumberChanged();
    partial void OnNumberSampleChanging(string value);
    partial void OnNumberSampleChanged();
    partial void OnLabIDChanging(string value);
    partial void OnLabIDChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnFilteredChanging(bool value);
    partial void OnFilteredChanged();
    partial void OnContainMetalChanging(bool value);
    partial void OnContainMetalChanged();
    partial void OnBoxNumberChanging(string value);
    partial void OnBoxNumberChanged();
    partial void OnVerifiedChanging(bool value);
    partial void OnVerifiedChanged();
    partial void OnLogDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLogDateChanged();
    partial void OnAnalyzeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnAnalyzeDateChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnUserCreatedChanging(string value);
    partial void OnUserCreatedChanged();
    partial void OnDateLastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastModifiedChanged();
    partial void OnUserLastModifiedChanging(string value);
    partial void OnUserLastModifiedChanged();
    partial void OnSampleIDChanging(System.Nullable<int> value);
    partial void OnSampleIDChanged();
    #endregion
		
		public tblMetalBarCode()
		{
			this._tblSample = default(EntityRef<tblSample>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetalBarCodeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MetalBarCodeID
		{
			get
			{
				return this._MetalBarCodeID;
			}
			set
			{
				if ((this._MetalBarCodeID != value))
				{
					this.OnMetalBarCodeIDChanging(value);
					this.SendPropertyChanging();
					this._MetalBarCodeID = value;
					this.SendPropertyChanged("MetalBarCodeID");
					this.OnMetalBarCodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleNumber", DbType="VarChar(30)")]
		public string SampleNumber
		{
			get
			{
				return this._SampleNumber;
			}
			set
			{
				if ((this._SampleNumber != value))
				{
					this.OnSampleNumberChanging(value);
					this.SendPropertyChanging();
					this._SampleNumber = value;
					this.SendPropertyChanged("SampleNumber");
					this.OnSampleNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberSample", DbType="VarChar(10)")]
		public string NumberSample
		{
			get
			{
				return this._NumberSample;
			}
			set
			{
				if ((this._NumberSample != value))
				{
					this.OnNumberSampleChanging(value);
					this.SendPropertyChanging();
					this._NumberSample = value;
					this.SendPropertyChanged("NumberSample");
					this.OnNumberSampleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LabID", DbType="VarChar(10)")]
		public string LabID
		{
			get
			{
				return this._LabID;
			}
			set
			{
				if ((this._LabID != value))
				{
					this.OnLabIDChanging(value);
					this.SendPropertyChanging();
					this._LabID = value;
					this.SendPropertyChanged("LabID");
					this.OnLabIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(2)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="VarChar(10)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filtered", DbType="Bit NOT NULL")]
		public bool Filtered
		{
			get
			{
				return this._Filtered;
			}
			set
			{
				if ((this._Filtered != value))
				{
					this.OnFilteredChanging(value);
					this.SendPropertyChanging();
					this._Filtered = value;
					this.SendPropertyChanged("Filtered");
					this.OnFilteredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContainMetal", DbType="Bit NOT NULL")]
		public bool ContainMetal
		{
			get
			{
				return this._ContainMetal;
			}
			set
			{
				if ((this._ContainMetal != value))
				{
					this.OnContainMetalChanging(value);
					this.SendPropertyChanging();
					this._ContainMetal = value;
					this.SendPropertyChanged("ContainMetal");
					this.OnContainMetalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BoxNumber", DbType="VarChar(5)")]
		public string BoxNumber
		{
			get
			{
				return this._BoxNumber;
			}
			set
			{
				if ((this._BoxNumber != value))
				{
					this.OnBoxNumberChanging(value);
					this.SendPropertyChanging();
					this._BoxNumber = value;
					this.SendPropertyChanged("BoxNumber");
					this.OnBoxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verified", DbType="Bit NOT NULL")]
		public bool Verified
		{
			get
			{
				return this._Verified;
			}
			set
			{
				if ((this._Verified != value))
				{
					this.OnVerifiedChanging(value);
					this.SendPropertyChanging();
					this._Verified = value;
					this.SendPropertyChanged("Verified");
					this.OnVerifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LogDate
		{
			get
			{
				return this._LogDate;
			}
			set
			{
				if ((this._LogDate != value))
				{
					this.OnLogDateChanging(value);
					this.SendPropertyChanging();
					this._LogDate = value;
					this.SendPropertyChanged("LogDate");
					this.OnLogDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnalyzeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> AnalyzeDate
		{
			get
			{
				return this._AnalyzeDate;
			}
			set
			{
				if ((this._AnalyzeDate != value))
				{
					this.OnAnalyzeDateChanging(value);
					this.SendPropertyChanging();
					this._AnalyzeDate = value;
					this.SendPropertyChanged("AnalyzeDate");
					this.OnAnalyzeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreated", DbType="VarChar(25)")]
		public string UserCreated
		{
			get
			{
				return this._UserCreated;
			}
			set
			{
				if ((this._UserCreated != value))
				{
					this.OnUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._UserCreated = value;
					this.SendPropertyChanged("UserCreated");
					this.OnUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastModified
		{
			get
			{
				return this._DateLastModified;
			}
			set
			{
				if ((this._DateLastModified != value))
				{
					this.OnDateLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateLastModified = value;
					this.SendPropertyChanged("DateLastModified");
					this.OnDateLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastModified", DbType="VarChar(25)")]
		public string UserLastModified
		{
			get
			{
				return this._UserLastModified;
			}
			set
			{
				if ((this._UserLastModified != value))
				{
					this.OnUserLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._UserLastModified = value;
					this.SendPropertyChanged("UserLastModified");
					this.OnUserLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleID", DbType="Int")]
		public System.Nullable<int> SampleID
		{
			get
			{
				return this._SampleID;
			}
			set
			{
				if ((this._SampleID != value))
				{
					if (this._tblSample.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSampleIDChanging(value);
					this.SendPropertyChanging();
					this._SampleID = value;
					this.SendPropertyChanged("SampleID");
					this.OnSampleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSample_tblMetalBarCode", Storage="_tblSample", ThisKey="SampleID", OtherKey="SampleID", IsForeignKey=true)]
		public tblSample tblSample
		{
			get
			{
				return this._tblSample.Entity;
			}
			set
			{
				tblSample previousValue = this._tblSample.Entity;
				if (((previousValue != value) 
							|| (this._tblSample.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSample.Entity = null;
						previousValue.tblMetalBarCodes.Remove(this);
					}
					this._tblSample.Entity = value;
					if ((value != null))
					{
						value.tblMetalBarCodes.Add(this);
						this._SampleID = value.SampleID;
					}
					else
					{
						this._SampleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblSample");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblInboundICP")]
	public partial class tblInboundICP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _inbICPID;
		
		private string _CODE;
		
		private string _DUPLICATE;
		
		private System.Nullable<decimal> _AL_D;
		
		private System.Nullable<decimal> _AL_T;
		
		private System.Nullable<decimal> _AS_D;
		
		private System.Nullable<decimal> _AS_T;
		
		private System.Nullable<decimal> _CA_D;
		
		private System.Nullable<decimal> _CA_T;
		
		private System.Nullable<decimal> _CD_D;
		
		private System.Nullable<decimal> _CD_T;
		
		private System.Nullable<decimal> _CU_D;
		
		private System.Nullable<decimal> _CU_T;
		
		private System.Nullable<decimal> _FE_D;
		
		private System.Nullable<decimal> _FE_T;
		
		private System.Nullable<decimal> _PB_D;
		
		private System.Nullable<decimal> _PB_T;
		
		private System.Nullable<decimal> _MG_D;
		
		private System.Nullable<decimal> _MG_T;
		
		private System.Nullable<decimal> _MN_D;
		
		private System.Nullable<decimal> _MN_T;
		
		private System.Nullable<decimal> _SE_D;
		
		private System.Nullable<decimal> _SE_T;
		
		private System.Nullable<decimal> _ZN_D;
		
		private System.Nullable<decimal> _ZN_T;
		
		private System.Nullable<decimal> _NA_D;
		
		private System.Nullable<decimal> _NA_T;
		
		private System.Nullable<decimal> _K_D;
		
		private System.Nullable<decimal> _K_T;
		
		private System.Nullable<System.DateTime> _ANADATE;
		
		private System.Nullable<bool> _COMPLETE;
		
		private System.Nullable<System.DateTime> _DATE_SENT;
		
		private string _Comments;
		
		private System.Nullable<decimal> _PassValStep;
		
		private bool _Reviewed;
		
		private string _FailedChems;
		
		private System.Nullable<int> _tblSampleID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninbICPIDChanging(int value);
    partial void OninbICPIDChanged();
    partial void OnCODEChanging(string value);
    partial void OnCODEChanged();
    partial void OnDUPLICATEChanging(string value);
    partial void OnDUPLICATEChanged();
    partial void OnAL_DChanging(System.Nullable<decimal> value);
    partial void OnAL_DChanged();
    partial void OnAL_TChanging(System.Nullable<decimal> value);
    partial void OnAL_TChanged();
    partial void OnAS_DChanging(System.Nullable<decimal> value);
    partial void OnAS_DChanged();
    partial void OnAS_TChanging(System.Nullable<decimal> value);
    partial void OnAS_TChanged();
    partial void OnCA_DChanging(System.Nullable<decimal> value);
    partial void OnCA_DChanged();
    partial void OnCA_TChanging(System.Nullable<decimal> value);
    partial void OnCA_TChanged();
    partial void OnCD_DChanging(System.Nullable<decimal> value);
    partial void OnCD_DChanged();
    partial void OnCD_TChanging(System.Nullable<decimal> value);
    partial void OnCD_TChanged();
    partial void OnCU_DChanging(System.Nullable<decimal> value);
    partial void OnCU_DChanged();
    partial void OnCU_TChanging(System.Nullable<decimal> value);
    partial void OnCU_TChanged();
    partial void OnFE_DChanging(System.Nullable<decimal> value);
    partial void OnFE_DChanged();
    partial void OnFE_TChanging(System.Nullable<decimal> value);
    partial void OnFE_TChanged();
    partial void OnPB_DChanging(System.Nullable<decimal> value);
    partial void OnPB_DChanged();
    partial void OnPB_TChanging(System.Nullable<decimal> value);
    partial void OnPB_TChanged();
    partial void OnMG_DChanging(System.Nullable<decimal> value);
    partial void OnMG_DChanged();
    partial void OnMG_TChanging(System.Nullable<decimal> value);
    partial void OnMG_TChanged();
    partial void OnMN_DChanging(System.Nullable<decimal> value);
    partial void OnMN_DChanged();
    partial void OnMN_TChanging(System.Nullable<decimal> value);
    partial void OnMN_TChanged();
    partial void OnSE_DChanging(System.Nullable<decimal> value);
    partial void OnSE_DChanged();
    partial void OnSE_TChanging(System.Nullable<decimal> value);
    partial void OnSE_TChanged();
    partial void OnZN_DChanging(System.Nullable<decimal> value);
    partial void OnZN_DChanged();
    partial void OnZN_TChanging(System.Nullable<decimal> value);
    partial void OnZN_TChanged();
    partial void OnNA_DChanging(System.Nullable<decimal> value);
    partial void OnNA_DChanged();
    partial void OnNA_TChanging(System.Nullable<decimal> value);
    partial void OnNA_TChanged();
    partial void OnK_DChanging(System.Nullable<decimal> value);
    partial void OnK_DChanged();
    partial void OnK_TChanging(System.Nullable<decimal> value);
    partial void OnK_TChanged();
    partial void OnANADATEChanging(System.Nullable<System.DateTime> value);
    partial void OnANADATEChanged();
    partial void OnCOMPLETEChanging(System.Nullable<bool> value);
    partial void OnCOMPLETEChanged();
    partial void OnDATE_SENTChanging(System.Nullable<System.DateTime> value);
    partial void OnDATE_SENTChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnPassValStepChanging(System.Nullable<decimal> value);
    partial void OnPassValStepChanged();
    partial void OnReviewedChanging(bool value);
    partial void OnReviewedChanged();
    partial void OnFailedChemsChanging(string value);
    partial void OnFailedChemsChanged();
    partial void OntblSampleIDChanging(System.Nullable<int> value);
    partial void OntblSampleIDChanged();
    #endregion
		
		public tblInboundICP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_inbICPID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int inbICPID
		{
			get
			{
				return this._inbICPID;
			}
			set
			{
				if ((this._inbICPID != value))
				{
					this.OninbICPIDChanging(value);
					this.SendPropertyChanging();
					this._inbICPID = value;
					this.SendPropertyChanged("inbICPID");
					this.OninbICPIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="VarChar(30)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this.OnCODEChanging(value);
					this.SendPropertyChanging();
					this._CODE = value;
					this.SendPropertyChanged("CODE");
					this.OnCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUPLICATE", DbType="Char(2)")]
		public string DUPLICATE
		{
			get
			{
				return this._DUPLICATE;
			}
			set
			{
				if ((this._DUPLICATE != value))
				{
					this.OnDUPLICATEChanging(value);
					this.SendPropertyChanging();
					this._DUPLICATE = value;
					this.SendPropertyChanged("DUPLICATE");
					this.OnDUPLICATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> AL_D
		{
			get
			{
				return this._AL_D;
			}
			set
			{
				if ((this._AL_D != value))
				{
					this.OnAL_DChanging(value);
					this.SendPropertyChanging();
					this._AL_D = value;
					this.SendPropertyChanged("AL_D");
					this.OnAL_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AL_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> AL_T
		{
			get
			{
				return this._AL_T;
			}
			set
			{
				if ((this._AL_T != value))
				{
					this.OnAL_TChanging(value);
					this.SendPropertyChanging();
					this._AL_T = value;
					this.SendPropertyChanged("AL_T");
					this.OnAL_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AS_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> AS_D
		{
			get
			{
				return this._AS_D;
			}
			set
			{
				if ((this._AS_D != value))
				{
					this.OnAS_DChanging(value);
					this.SendPropertyChanging();
					this._AS_D = value;
					this.SendPropertyChanged("AS_D");
					this.OnAS_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AS_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> AS_T
		{
			get
			{
				return this._AS_T;
			}
			set
			{
				if ((this._AS_T != value))
				{
					this.OnAS_TChanging(value);
					this.SendPropertyChanging();
					this._AS_T = value;
					this.SendPropertyChanged("AS_T");
					this.OnAS_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CA_D
		{
			get
			{
				return this._CA_D;
			}
			set
			{
				if ((this._CA_D != value))
				{
					this.OnCA_DChanging(value);
					this.SendPropertyChanging();
					this._CA_D = value;
					this.SendPropertyChanged("CA_D");
					this.OnCA_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CA_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CA_T
		{
			get
			{
				return this._CA_T;
			}
			set
			{
				if ((this._CA_T != value))
				{
					this.OnCA_TChanging(value);
					this.SendPropertyChanging();
					this._CA_T = value;
					this.SendPropertyChanged("CA_T");
					this.OnCA_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CD_D
		{
			get
			{
				return this._CD_D;
			}
			set
			{
				if ((this._CD_D != value))
				{
					this.OnCD_DChanging(value);
					this.SendPropertyChanging();
					this._CD_D = value;
					this.SendPropertyChanged("CD_D");
					this.OnCD_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CD_T
		{
			get
			{
				return this._CD_T;
			}
			set
			{
				if ((this._CD_T != value))
				{
					this.OnCD_TChanging(value);
					this.SendPropertyChanging();
					this._CD_T = value;
					this.SendPropertyChanged("CD_T");
					this.OnCD_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CU_D
		{
			get
			{
				return this._CU_D;
			}
			set
			{
				if ((this._CU_D != value))
				{
					this.OnCU_DChanging(value);
					this.SendPropertyChanging();
					this._CU_D = value;
					this.SendPropertyChanged("CU_D");
					this.OnCU_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CU_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> CU_T
		{
			get
			{
				return this._CU_T;
			}
			set
			{
				if ((this._CU_T != value))
				{
					this.OnCU_TChanging(value);
					this.SendPropertyChanging();
					this._CU_T = value;
					this.SendPropertyChanged("CU_T");
					this.OnCU_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> FE_D
		{
			get
			{
				return this._FE_D;
			}
			set
			{
				if ((this._FE_D != value))
				{
					this.OnFE_DChanging(value);
					this.SendPropertyChanging();
					this._FE_D = value;
					this.SendPropertyChanged("FE_D");
					this.OnFE_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FE_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> FE_T
		{
			get
			{
				return this._FE_T;
			}
			set
			{
				if ((this._FE_T != value))
				{
					this.OnFE_TChanging(value);
					this.SendPropertyChanging();
					this._FE_T = value;
					this.SendPropertyChanged("FE_T");
					this.OnFE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PB_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> PB_D
		{
			get
			{
				return this._PB_D;
			}
			set
			{
				if ((this._PB_D != value))
				{
					this.OnPB_DChanging(value);
					this.SendPropertyChanging();
					this._PB_D = value;
					this.SendPropertyChanged("PB_D");
					this.OnPB_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PB_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> PB_T
		{
			get
			{
				return this._PB_T;
			}
			set
			{
				if ((this._PB_T != value))
				{
					this.OnPB_TChanging(value);
					this.SendPropertyChanging();
					this._PB_T = value;
					this.SendPropertyChanged("PB_T");
					this.OnPB_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MG_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> MG_D
		{
			get
			{
				return this._MG_D;
			}
			set
			{
				if ((this._MG_D != value))
				{
					this.OnMG_DChanging(value);
					this.SendPropertyChanging();
					this._MG_D = value;
					this.SendPropertyChanged("MG_D");
					this.OnMG_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MG_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> MG_T
		{
			get
			{
				return this._MG_T;
			}
			set
			{
				if ((this._MG_T != value))
				{
					this.OnMG_TChanging(value);
					this.SendPropertyChanging();
					this._MG_T = value;
					this.SendPropertyChanged("MG_T");
					this.OnMG_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MN_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> MN_D
		{
			get
			{
				return this._MN_D;
			}
			set
			{
				if ((this._MN_D != value))
				{
					this.OnMN_DChanging(value);
					this.SendPropertyChanging();
					this._MN_D = value;
					this.SendPropertyChanged("MN_D");
					this.OnMN_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MN_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> MN_T
		{
			get
			{
				return this._MN_T;
			}
			set
			{
				if ((this._MN_T != value))
				{
					this.OnMN_TChanging(value);
					this.SendPropertyChanging();
					this._MN_T = value;
					this.SendPropertyChanged("MN_T");
					this.OnMN_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SE_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> SE_D
		{
			get
			{
				return this._SE_D;
			}
			set
			{
				if ((this._SE_D != value))
				{
					this.OnSE_DChanging(value);
					this.SendPropertyChanging();
					this._SE_D = value;
					this.SendPropertyChanged("SE_D");
					this.OnSE_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SE_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> SE_T
		{
			get
			{
				return this._SE_T;
			}
			set
			{
				if ((this._SE_T != value))
				{
					this.OnSE_TChanging(value);
					this.SendPropertyChanging();
					this._SE_T = value;
					this.SendPropertyChanged("SE_T");
					this.OnSE_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZN_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> ZN_D
		{
			get
			{
				return this._ZN_D;
			}
			set
			{
				if ((this._ZN_D != value))
				{
					this.OnZN_DChanging(value);
					this.SendPropertyChanging();
					this._ZN_D = value;
					this.SendPropertyChanged("ZN_D");
					this.OnZN_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZN_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> ZN_T
		{
			get
			{
				return this._ZN_T;
			}
			set
			{
				if ((this._ZN_T != value))
				{
					this.OnZN_TChanging(value);
					this.SendPropertyChanging();
					this._ZN_T = value;
					this.SendPropertyChanged("ZN_T");
					this.OnZN_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NA_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> NA_D
		{
			get
			{
				return this._NA_D;
			}
			set
			{
				if ((this._NA_D != value))
				{
					this.OnNA_DChanging(value);
					this.SendPropertyChanging();
					this._NA_D = value;
					this.SendPropertyChanged("NA_D");
					this.OnNA_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NA_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> NA_T
		{
			get
			{
				return this._NA_T;
			}
			set
			{
				if ((this._NA_T != value))
				{
					this.OnNA_TChanging(value);
					this.SendPropertyChanging();
					this._NA_T = value;
					this.SendPropertyChanged("NA_T");
					this.OnNA_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_K_D", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> K_D
		{
			get
			{
				return this._K_D;
			}
			set
			{
				if ((this._K_D != value))
				{
					this.OnK_DChanging(value);
					this.SendPropertyChanging();
					this._K_D = value;
					this.SendPropertyChanged("K_D");
					this.OnK_DChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_K_T", DbType="Decimal(12,6)")]
		public System.Nullable<decimal> K_T
		{
			get
			{
				return this._K_T;
			}
			set
			{
				if ((this._K_T != value))
				{
					this.OnK_TChanging(value);
					this.SendPropertyChanging();
					this._K_T = value;
					this.SendPropertyChanged("K_T");
					this.OnK_TChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANADATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> ANADATE
		{
			get
			{
				return this._ANADATE;
			}
			set
			{
				if ((this._ANADATE != value))
				{
					this.OnANADATEChanging(value);
					this.SendPropertyChanging();
					this._ANADATE = value;
					this.SendPropertyChanged("ANADATE");
					this.OnANADATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPLETE", DbType="Bit")]
		public System.Nullable<bool> COMPLETE
		{
			get
			{
				return this._COMPLETE;
			}
			set
			{
				if ((this._COMPLETE != value))
				{
					this.OnCOMPLETEChanging(value);
					this.SendPropertyChanging();
					this._COMPLETE = value;
					this.SendPropertyChanged("COMPLETE");
					this.OnCOMPLETEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DATE_SENT", DbType="DateTime")]
		public System.Nullable<System.DateTime> DATE_SENT
		{
			get
			{
				return this._DATE_SENT;
			}
			set
			{
				if ((this._DATE_SENT != value))
				{
					this.OnDATE_SENTChanging(value);
					this.SendPropertyChanging();
					this._DATE_SENT = value;
					this.SendPropertyChanged("DATE_SENT");
					this.OnDATE_SENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(100)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassValStep", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> PassValStep
		{
			get
			{
				return this._PassValStep;
			}
			set
			{
				if ((this._PassValStep != value))
				{
					this.OnPassValStepChanging(value);
					this.SendPropertyChanging();
					this._PassValStep = value;
					this.SendPropertyChanged("PassValStep");
					this.OnPassValStepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reviewed", DbType="Bit NOT NULL")]
		public bool Reviewed
		{
			get
			{
				return this._Reviewed;
			}
			set
			{
				if ((this._Reviewed != value))
				{
					this.OnReviewedChanging(value);
					this.SendPropertyChanging();
					this._Reviewed = value;
					this.SendPropertyChanged("Reviewed");
					this.OnReviewedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedChems", DbType="VarChar(200)")]
		public string FailedChems
		{
			get
			{
				return this._FailedChems;
			}
			set
			{
				if ((this._FailedChems != value))
				{
					this.OnFailedChemsChanging(value);
					this.SendPropertyChanging();
					this._FailedChems = value;
					this.SendPropertyChanged("FailedChems");
					this.OnFailedChemsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tblSampleID", DbType="Int")]
		public System.Nullable<int> tblSampleID
		{
			get
			{
				return this._tblSampleID;
			}
			set
			{
				if ((this._tblSampleID != value))
				{
					this.OntblSampleIDChanging(value);
					this.SendPropertyChanging();
					this._tblSampleID = value;
					this.SendPropertyChanged("tblSampleID");
					this.OntblSampleIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChemValues")]
	public partial class tblChemValue : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChemSampID;
		
		private int _RepNum;
		
		private int _ChemParamID;
		
		private System.Nullable<double> _ChemValue;
		
		private string _Comments;
		
		private System.Nullable<System.DateTime> _EnterDate;
		
		private string _StoretUploaded;
		
		private EntityRef<tblChemSamp> _tblChemSamp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChemSampIDChanging(int value);
    partial void OnChemSampIDChanged();
    partial void OnRepNumChanging(int value);
    partial void OnRepNumChanged();
    partial void OnChemParamIDChanging(int value);
    partial void OnChemParamIDChanged();
    partial void OnChemValueChanging(System.Nullable<double> value);
    partial void OnChemValueChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    partial void OnStoretUploadedChanging(string value);
    partial void OnStoretUploadedChanged();
    #endregion
		
		public tblChemValue()
		{
			this._tblChemSamp = default(EntityRef<tblChemSamp>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChemSampID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ChemSampID
		{
			get
			{
				return this._ChemSampID;
			}
			set
			{
				if ((this._ChemSampID != value))
				{
					if (this._tblChemSamp.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnChemSampIDChanging(value);
					this.SendPropertyChanging();
					this._ChemSampID = value;
					this.SendPropertyChanged("ChemSampID");
					this.OnChemSampIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RepNum", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int RepNum
		{
			get
			{
				return this._RepNum;
			}
			set
			{
				if ((this._RepNum != value))
				{
					this.OnRepNumChanging(value);
					this.SendPropertyChanging();
					this._RepNum = value;
					this.SendPropertyChanged("RepNum");
					this.OnRepNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChemParamID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ChemParamID
		{
			get
			{
				return this._ChemParamID;
			}
			set
			{
				if ((this._ChemParamID != value))
				{
					this.OnChemParamIDChanging(value);
					this.SendPropertyChanging();
					this._ChemParamID = value;
					this.SendPropertyChanged("ChemParamID");
					this.OnChemParamIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChemValue", DbType="Float")]
		public System.Nullable<double> ChemValue
		{
			get
			{
				return this._ChemValue;
			}
			set
			{
				if ((this._ChemValue != value))
				{
					this.OnChemValueChanging(value);
					this.SendPropertyChanging();
					this._ChemValue = value;
					this.SendPropertyChanged("ChemValue");
					this.OnChemValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(255)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnterDate
		{
			get
			{
				return this._EnterDate;
			}
			set
			{
				if ((this._EnterDate != value))
				{
					this.OnEnterDateChanging(value);
					this.SendPropertyChanging();
					this._EnterDate = value;
					this.SendPropertyChanged("EnterDate");
					this.OnEnterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoretUploaded", DbType="VarChar(25)")]
		public string StoretUploaded
		{
			get
			{
				return this._StoretUploaded;
			}
			set
			{
				if ((this._StoretUploaded != value))
				{
					this.OnStoretUploadedChanging(value);
					this.SendPropertyChanging();
					this._StoretUploaded = value;
					this.SendPropertyChanged("StoretUploaded");
					this.OnStoretUploadedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChemSamp_tblChemValue", Storage="_tblChemSamp", ThisKey="ChemSampID", OtherKey="ChemSampID", IsForeignKey=true)]
		public tblChemSamp tblChemSamp
		{
			get
			{
				return this._tblChemSamp.Entity;
			}
			set
			{
				tblChemSamp previousValue = this._tblChemSamp.Entity;
				if (((previousValue != value) 
							|| (this._tblChemSamp.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblChemSamp.Entity = null;
						previousValue.tblChemValues.Remove(this);
					}
					this._tblChemSamp.Entity = value;
					if ((value != null))
					{
						value.tblChemValues.Add(this);
						this._ChemSampID = value.ChemSampID;
					}
					else
					{
						this._ChemSampID = default(int);
					}
					this.SendPropertyChanged("tblChemSamp");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChemSamps")]
	public partial class tblChemSamp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ChemSampID;
		
		private System.Nullable<int> _SampleID;
		
		private string _ActivityType;
		
		private string _ActivityID;
		
		private System.Nullable<System.DateTime> _CollDate;
		
		private System.Nullable<int> _CollMeth;
		
		private string _FieldGearID;
		
		private System.Nullable<int> _GearConfigID;
		
		private System.Nullable<int> _Medium;
		
		private string _Comments;
		
		private System.Nullable<System.DateTime> _EnterDate;
		
		private EntitySet<tblChemValue> _tblChemValues;
		
		private EntityRef<tblSample> _tblSample;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnChemSampIDChanging(int value);
    partial void OnChemSampIDChanged();
    partial void OnSampleIDChanging(System.Nullable<int> value);
    partial void OnSampleIDChanged();
    partial void OnActivityTypeChanging(string value);
    partial void OnActivityTypeChanged();
    partial void OnActivityIDChanging(string value);
    partial void OnActivityIDChanged();
    partial void OnCollDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCollDateChanged();
    partial void OnCollMethChanging(System.Nullable<int> value);
    partial void OnCollMethChanged();
    partial void OnFieldGearIDChanging(string value);
    partial void OnFieldGearIDChanged();
    partial void OnGearConfigIDChanging(System.Nullable<int> value);
    partial void OnGearConfigIDChanged();
    partial void OnMediumChanging(System.Nullable<int> value);
    partial void OnMediumChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    partial void OnEnterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEnterDateChanged();
    #endregion
		
		public tblChemSamp()
		{
			this._tblChemValues = new EntitySet<tblChemValue>(new Action<tblChemValue>(this.attach_tblChemValues), new Action<tblChemValue>(this.detach_tblChemValues));
			this._tblSample = default(EntityRef<tblSample>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChemSampID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ChemSampID
		{
			get
			{
				return this._ChemSampID;
			}
			set
			{
				if ((this._ChemSampID != value))
				{
					this.OnChemSampIDChanging(value);
					this.SendPropertyChanging();
					this._ChemSampID = value;
					this.SendPropertyChanged("ChemSampID");
					this.OnChemSampIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleID", DbType="Int")]
		public System.Nullable<int> SampleID
		{
			get
			{
				return this._SampleID;
			}
			set
			{
				if ((this._SampleID != value))
				{
					if (this._tblSample.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSampleIDChanging(value);
					this.SendPropertyChanging();
					this._SampleID = value;
					this.SendPropertyChanged("SampleID");
					this.OnSampleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityType", DbType="VarChar(15)")]
		public string ActivityType
		{
			get
			{
				return this._ActivityType;
			}
			set
			{
				if ((this._ActivityType != value))
				{
					this.OnActivityTypeChanging(value);
					this.SendPropertyChanging();
					this._ActivityType = value;
					this.SendPropertyChanged("ActivityType");
					this.OnActivityTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActivityID", DbType="VarChar(12)")]
		public string ActivityID
		{
			get
			{
				return this._ActivityID;
			}
			set
			{
				if ((this._ActivityID != value))
				{
					this.OnActivityIDChanging(value);
					this.SendPropertyChanging();
					this._ActivityID = value;
					this.SendPropertyChanged("ActivityID");
					this.OnActivityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CollDate
		{
			get
			{
				return this._CollDate;
			}
			set
			{
				if ((this._CollDate != value))
				{
					this.OnCollDateChanging(value);
					this.SendPropertyChanging();
					this._CollDate = value;
					this.SendPropertyChanged("CollDate");
					this.OnCollDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CollMeth", DbType="Int")]
		public System.Nullable<int> CollMeth
		{
			get
			{
				return this._CollMeth;
			}
			set
			{
				if ((this._CollMeth != value))
				{
					this.OnCollMethChanging(value);
					this.SendPropertyChanging();
					this._CollMeth = value;
					this.SendPropertyChanged("CollMeth");
					this.OnCollMethChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FieldGearID", DbType="VarChar(10)")]
		public string FieldGearID
		{
			get
			{
				return this._FieldGearID;
			}
			set
			{
				if ((this._FieldGearID != value))
				{
					this.OnFieldGearIDChanging(value);
					this.SendPropertyChanging();
					this._FieldGearID = value;
					this.SendPropertyChanged("FieldGearID");
					this.OnFieldGearIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GearConfigID", DbType="Int")]
		public System.Nullable<int> GearConfigID
		{
			get
			{
				return this._GearConfigID;
			}
			set
			{
				if ((this._GearConfigID != value))
				{
					this.OnGearConfigIDChanging(value);
					this.SendPropertyChanging();
					this._GearConfigID = value;
					this.SendPropertyChanged("GearConfigID");
					this.OnGearConfigIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medium", DbType="Int")]
		public System.Nullable<int> Medium
		{
			get
			{
				return this._Medium;
			}
			set
			{
				if ((this._Medium != value))
				{
					this.OnMediumChanging(value);
					this.SendPropertyChanging();
					this._Medium = value;
					this.SendPropertyChanged("Medium");
					this.OnMediumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="VarChar(255)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnterDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EnterDate
		{
			get
			{
				return this._EnterDate;
			}
			set
			{
				if ((this._EnterDate != value))
				{
					this.OnEnterDateChanging(value);
					this.SendPropertyChanging();
					this._EnterDate = value;
					this.SendPropertyChanged("EnterDate");
					this.OnEnterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblChemSamp_tblChemValue", Storage="_tblChemValues", ThisKey="ChemSampID", OtherKey="ChemSampID")]
		public EntitySet<tblChemValue> tblChemValues
		{
			get
			{
				return this._tblChemValues;
			}
			set
			{
				this._tblChemValues.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSample_tblChemSamp", Storage="_tblSample", ThisKey="SampleID", OtherKey="SampleID", IsForeignKey=true)]
		public tblSample tblSample
		{
			get
			{
				return this._tblSample.Entity;
			}
			set
			{
				tblSample previousValue = this._tblSample.Entity;
				if (((previousValue != value) 
							|| (this._tblSample.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSample.Entity = null;
						previousValue.tblChemSamps.Remove(this);
					}
					this._tblSample.Entity = value;
					if ((value != null))
					{
						value.tblChemSamps.Add(this);
						this._SampleID = value.SampleID;
					}
					else
					{
						this._SampleID = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblSample");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChemValues(tblChemValue entity)
		{
			this.SendPropertyChanging();
			entity.tblChemSamp = this;
		}
		
		private void detach_tblChemValues(tblChemValue entity)
		{
			this.SendPropertyChanging();
			entity.tblChemSamp = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSample")]
	public partial class tblSample : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SampleID;
		
		private int _StationID;
		
		private System.Nullable<int> _OrganizationID;
		
		private string _SampleNumber;
		
		private string _NumberSample;
		
		private System.DateTime _DateCollected;
		
		private System.Nullable<System.DateTime> _TimeCollected;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private bool _DataSheetIncluded;
		
		private System.Nullable<System.DateTime> _MissingDataSheetReqDate;
		
		private bool _ChainOfCustody;
		
		private bool _MissingDataSheetReceived;
		
		private bool _NoMetals;
		
		private bool _PhysicalHabitat;
		
		private bool _Bug;
		
		private bool _NoNutrient;
		
		private decimal _TotalSuspendedSolids;
		
		private bool _NitratePhosphorus;
		
		private bool _DuplicatedTSS;
		
		private bool _DuplicatedNP;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _DateCreated;
		
		private string _UserCreated;
		
		private System.Nullable<System.DateTime> _DateLastModified;
		
		private string _UserLastModified;
		
		private System.Nullable<bool> _ChlorideSulfate;
		
		private System.Nullable<bool> _BlankMetals;
		
		private System.Nullable<bool> _DuplicatedMetals;
		
		private System.Nullable<bool> _BugsQA;
		
		private System.Nullable<bool> _DuplicatedCS;
		
		private EntitySet<tblMetalBarCode> _tblMetalBarCodes;
		
		private EntitySet<tblChemSamp> _tblChemSamps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSampleIDChanging(int value);
    partial void OnSampleIDChanged();
    partial void OnStationIDChanging(int value);
    partial void OnStationIDChanged();
    partial void OnOrganizationIDChanging(System.Nullable<int> value);
    partial void OnOrganizationIDChanged();
    partial void OnSampleNumberChanging(string value);
    partial void OnSampleNumberChanged();
    partial void OnNumberSampleChanging(string value);
    partial void OnNumberSampleChanged();
    partial void OnDateCollectedChanging(System.DateTime value);
    partial void OnDateCollectedChanged();
    partial void OnTimeCollectedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeCollectedChanged();
    partial void OnDateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReceivedChanged();
    partial void OnDataSheetIncludedChanging(bool value);
    partial void OnDataSheetIncludedChanged();
    partial void OnMissingDataSheetReqDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMissingDataSheetReqDateChanged();
    partial void OnChainOfCustodyChanging(bool value);
    partial void OnChainOfCustodyChanged();
    partial void OnMissingDataSheetReceivedChanging(bool value);
    partial void OnMissingDataSheetReceivedChanged();
    partial void OnNoMetalsChanging(bool value);
    partial void OnNoMetalsChanged();
    partial void OnPhysicalHabitatChanging(bool value);
    partial void OnPhysicalHabitatChanged();
    partial void OnBugChanging(bool value);
    partial void OnBugChanged();
    partial void OnNoNutrientChanging(bool value);
    partial void OnNoNutrientChanged();
    partial void OnTotalSuspendedSolidsChanging(decimal value);
    partial void OnTotalSuspendedSolidsChanged();
    partial void OnNitratePhosphorusChanging(bool value);
    partial void OnNitratePhosphorusChanged();
    partial void OnDuplicatedTSSChanging(bool value);
    partial void OnDuplicatedTSSChanged();
    partial void OnDuplicatedNPChanging(bool value);
    partial void OnDuplicatedNPChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnDateCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCreatedChanged();
    partial void OnUserCreatedChanging(string value);
    partial void OnUserCreatedChanged();
    partial void OnDateLastModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateLastModifiedChanged();
    partial void OnUserLastModifiedChanging(string value);
    partial void OnUserLastModifiedChanged();
    partial void OnChlorideSulfateChanging(System.Nullable<bool> value);
    partial void OnChlorideSulfateChanged();
    partial void OnBlankMetalsChanging(System.Nullable<bool> value);
    partial void OnBlankMetalsChanged();
    partial void OnDuplicatedMetalsChanging(System.Nullable<bool> value);
    partial void OnDuplicatedMetalsChanged();
    partial void OnBugsQAChanging(System.Nullable<bool> value);
    partial void OnBugsQAChanged();
    partial void OnDuplicatedCSChanging(System.Nullable<bool> value);
    partial void OnDuplicatedCSChanged();
    #endregion
		
		public tblSample()
		{
			this._tblMetalBarCodes = new EntitySet<tblMetalBarCode>(new Action<tblMetalBarCode>(this.attach_tblMetalBarCodes), new Action<tblMetalBarCode>(this.detach_tblMetalBarCodes));
			this._tblChemSamps = new EntitySet<tblChemSamp>(new Action<tblChemSamp>(this.attach_tblChemSamps), new Action<tblChemSamp>(this.detach_tblChemSamps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SampleID
		{
			get
			{
				return this._SampleID;
			}
			set
			{
				if ((this._SampleID != value))
				{
					this.OnSampleIDChanging(value);
					this.SendPropertyChanging();
					this._SampleID = value;
					this.SendPropertyChanged("SampleID");
					this.OnSampleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="Int NOT NULL")]
		public int StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationID", DbType="Int")]
		public System.Nullable<int> OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SampleNumber", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SampleNumber
		{
			get
			{
				return this._SampleNumber;
			}
			set
			{
				if ((this._SampleNumber != value))
				{
					this.OnSampleNumberChanging(value);
					this.SendPropertyChanging();
					this._SampleNumber = value;
					this.SendPropertyChanged("SampleNumber");
					this.OnSampleNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberSample", DbType="VarChar(10)")]
		public string NumberSample
		{
			get
			{
				return this._NumberSample;
			}
			set
			{
				if ((this._NumberSample != value))
				{
					this.OnNumberSampleChanging(value);
					this.SendPropertyChanging();
					this._NumberSample = value;
					this.SendPropertyChanged("NumberSample");
					this.OnNumberSampleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCollected", DbType="DateTime NOT NULL")]
		public System.DateTime DateCollected
		{
			get
			{
				return this._DateCollected;
			}
			set
			{
				if ((this._DateCollected != value))
				{
					this.OnDateCollectedChanging(value);
					this.SendPropertyChanging();
					this._DateCollected = value;
					this.SendPropertyChanged("DateCollected");
					this.OnDateCollectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCollected", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeCollected
		{
			get
			{
				return this._TimeCollected;
			}
			set
			{
				if ((this._TimeCollected != value))
				{
					this.OnTimeCollectedChanging(value);
					this.SendPropertyChanging();
					this._TimeCollected = value;
					this.SendPropertyChanged("TimeCollected");
					this.OnTimeCollectedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this.OnDateReceivedChanging(value);
					this.SendPropertyChanging();
					this._DateReceived = value;
					this.SendPropertyChanged("DateReceived");
					this.OnDateReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataSheetIncluded", DbType="Bit NOT NULL")]
		public bool DataSheetIncluded
		{
			get
			{
				return this._DataSheetIncluded;
			}
			set
			{
				if ((this._DataSheetIncluded != value))
				{
					this.OnDataSheetIncludedChanging(value);
					this.SendPropertyChanging();
					this._DataSheetIncluded = value;
					this.SendPropertyChanged("DataSheetIncluded");
					this.OnDataSheetIncludedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MissingDataSheetReqDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MissingDataSheetReqDate
		{
			get
			{
				return this._MissingDataSheetReqDate;
			}
			set
			{
				if ((this._MissingDataSheetReqDate != value))
				{
					this.OnMissingDataSheetReqDateChanging(value);
					this.SendPropertyChanging();
					this._MissingDataSheetReqDate = value;
					this.SendPropertyChanged("MissingDataSheetReqDate");
					this.OnMissingDataSheetReqDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChainOfCustody", DbType="Bit NOT NULL")]
		public bool ChainOfCustody
		{
			get
			{
				return this._ChainOfCustody;
			}
			set
			{
				if ((this._ChainOfCustody != value))
				{
					this.OnChainOfCustodyChanging(value);
					this.SendPropertyChanging();
					this._ChainOfCustody = value;
					this.SendPropertyChanged("ChainOfCustody");
					this.OnChainOfCustodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MissingDataSheetReceived", DbType="Bit NOT NULL")]
		public bool MissingDataSheetReceived
		{
			get
			{
				return this._MissingDataSheetReceived;
			}
			set
			{
				if ((this._MissingDataSheetReceived != value))
				{
					this.OnMissingDataSheetReceivedChanging(value);
					this.SendPropertyChanging();
					this._MissingDataSheetReceived = value;
					this.SendPropertyChanged("MissingDataSheetReceived");
					this.OnMissingDataSheetReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoMetals", DbType="Bit NOT NULL")]
		public bool NoMetals
		{
			get
			{
				return this._NoMetals;
			}
			set
			{
				if ((this._NoMetals != value))
				{
					this.OnNoMetalsChanging(value);
					this.SendPropertyChanging();
					this._NoMetals = value;
					this.SendPropertyChanged("NoMetals");
					this.OnNoMetalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalHabitat", DbType="Bit NOT NULL")]
		public bool PhysicalHabitat
		{
			get
			{
				return this._PhysicalHabitat;
			}
			set
			{
				if ((this._PhysicalHabitat != value))
				{
					this.OnPhysicalHabitatChanging(value);
					this.SendPropertyChanging();
					this._PhysicalHabitat = value;
					this.SendPropertyChanged("PhysicalHabitat");
					this.OnPhysicalHabitatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bug", DbType="Bit NOT NULL")]
		public bool Bug
		{
			get
			{
				return this._Bug;
			}
			set
			{
				if ((this._Bug != value))
				{
					this.OnBugChanging(value);
					this.SendPropertyChanging();
					this._Bug = value;
					this.SendPropertyChanged("Bug");
					this.OnBugChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoNutrient", DbType="Bit NOT NULL")]
		public bool NoNutrient
		{
			get
			{
				return this._NoNutrient;
			}
			set
			{
				if ((this._NoNutrient != value))
				{
					this.OnNoNutrientChanging(value);
					this.SendPropertyChanging();
					this._NoNutrient = value;
					this.SendPropertyChanged("NoNutrient");
					this.OnNoNutrientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSuspendedSolids", DbType="Bit NOT NULL")]
		public decimal TotalSuspendedSolids
		{
			get
			{
				return this._TotalSuspendedSolids;
			}
			set
			{
				if ((this._TotalSuspendedSolids != value))
				{
					this.OnTotalSuspendedSolidsChanging(value);
					this.SendPropertyChanging();
					this._TotalSuspendedSolids = value;
					this.SendPropertyChanged("TotalSuspendedSolids");
					this.OnTotalSuspendedSolidsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NitratePhosphorus", DbType="Bit NOT NULL")]
		public bool NitratePhosphorus
		{
			get
			{
				return this._NitratePhosphorus;
			}
			set
			{
				if ((this._NitratePhosphorus != value))
				{
					this.OnNitratePhosphorusChanging(value);
					this.SendPropertyChanging();
					this._NitratePhosphorus = value;
					this.SendPropertyChanged("NitratePhosphorus");
					this.OnNitratePhosphorusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuplicatedTSS", DbType="Bit NOT NULL")]
		public bool DuplicatedTSS
		{
			get
			{
				return this._DuplicatedTSS;
			}
			set
			{
				if ((this._DuplicatedTSS != value))
				{
					this.OnDuplicatedTSSChanging(value);
					this.SendPropertyChanging();
					this._DuplicatedTSS = value;
					this.SendPropertyChanged("DuplicatedTSS");
					this.OnDuplicatedTSSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuplicatedNP", DbType="Bit NOT NULL")]
		public bool DuplicatedNP
		{
			get
			{
				return this._DuplicatedNP;
			}
			set
			{
				if ((this._DuplicatedNP != value))
				{
					this.OnDuplicatedNPChanging(value);
					this.SendPropertyChanging();
					this._DuplicatedNP = value;
					this.SendPropertyChanged("DuplicatedNP");
					this.OnDuplicatedNPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="VarChar(1000)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCreated
		{
			get
			{
				return this._DateCreated;
			}
			set
			{
				if ((this._DateCreated != value))
				{
					this.OnDateCreatedChanging(value);
					this.SendPropertyChanging();
					this._DateCreated = value;
					this.SendPropertyChanged("DateCreated");
					this.OnDateCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCreated", DbType="VarChar(25)")]
		public string UserCreated
		{
			get
			{
				return this._UserCreated;
			}
			set
			{
				if ((this._UserCreated != value))
				{
					this.OnUserCreatedChanging(value);
					this.SendPropertyChanging();
					this._UserCreated = value;
					this.SendPropertyChanged("UserCreated");
					this.OnUserCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLastModified", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateLastModified
		{
			get
			{
				return this._DateLastModified;
			}
			set
			{
				if ((this._DateLastModified != value))
				{
					this.OnDateLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._DateLastModified = value;
					this.SendPropertyChanged("DateLastModified");
					this.OnDateLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserLastModified", DbType="VarChar(25)")]
		public string UserLastModified
		{
			get
			{
				return this._UserLastModified;
			}
			set
			{
				if ((this._UserLastModified != value))
				{
					this.OnUserLastModifiedChanging(value);
					this.SendPropertyChanging();
					this._UserLastModified = value;
					this.SendPropertyChanged("UserLastModified");
					this.OnUserLastModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChlorideSulfate", DbType="Bit")]
		public System.Nullable<bool> ChlorideSulfate
		{
			get
			{
				return this._ChlorideSulfate;
			}
			set
			{
				if ((this._ChlorideSulfate != value))
				{
					this.OnChlorideSulfateChanging(value);
					this.SendPropertyChanging();
					this._ChlorideSulfate = value;
					this.SendPropertyChanged("ChlorideSulfate");
					this.OnChlorideSulfateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BlankMetals", DbType="Bit")]
		public System.Nullable<bool> BlankMetals
		{
			get
			{
				return this._BlankMetals;
			}
			set
			{
				if ((this._BlankMetals != value))
				{
					this.OnBlankMetalsChanging(value);
					this.SendPropertyChanging();
					this._BlankMetals = value;
					this.SendPropertyChanged("BlankMetals");
					this.OnBlankMetalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuplicatedMetals", DbType="Bit")]
		public System.Nullable<bool> DuplicatedMetals
		{
			get
			{
				return this._DuplicatedMetals;
			}
			set
			{
				if ((this._DuplicatedMetals != value))
				{
					this.OnDuplicatedMetalsChanging(value);
					this.SendPropertyChanging();
					this._DuplicatedMetals = value;
					this.SendPropertyChanged("DuplicatedMetals");
					this.OnDuplicatedMetalsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BugsQA", DbType="Bit")]
		public System.Nullable<bool> BugsQA
		{
			get
			{
				return this._BugsQA;
			}
			set
			{
				if ((this._BugsQA != value))
				{
					this.OnBugsQAChanging(value);
					this.SendPropertyChanging();
					this._BugsQA = value;
					this.SendPropertyChanged("BugsQA");
					this.OnBugsQAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DuplicatedCS", DbType="Bit")]
		public System.Nullable<bool> DuplicatedCS
		{
			get
			{
				return this._DuplicatedCS;
			}
			set
			{
				if ((this._DuplicatedCS != value))
				{
					this.OnDuplicatedCSChanging(value);
					this.SendPropertyChanging();
					this._DuplicatedCS = value;
					this.SendPropertyChanged("DuplicatedCS");
					this.OnDuplicatedCSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSample_tblMetalBarCode", Storage="_tblMetalBarCodes", ThisKey="SampleID", OtherKey="SampleID")]
		public EntitySet<tblMetalBarCode> tblMetalBarCodes
		{
			get
			{
				return this._tblMetalBarCodes;
			}
			set
			{
				this._tblMetalBarCodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSample_tblChemSamp", Storage="_tblChemSamps", ThisKey="SampleID", OtherKey="SampleID")]
		public EntitySet<tblChemSamp> tblChemSamps
		{
			get
			{
				return this._tblChemSamps;
			}
			set
			{
				this._tblChemSamps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblMetalBarCodes(tblMetalBarCode entity)
		{
			this.SendPropertyChanging();
			entity.tblSample = this;
		}
		
		private void detach_tblMetalBarCodes(tblMetalBarCode entity)
		{
			this.SendPropertyChanging();
			entity.tblSample = null;
		}
		
		private void attach_tblChemSamps(tblChemSamp entity)
		{
			this.SendPropertyChanging();
			entity.tblSample = this;
		}
		
		private void detach_tblChemSamps(tblChemSamp entity)
		{
			this.SendPropertyChanging();
			entity.tblSample = null;
		}
	}
}
#pragma warning restore 1591
